# Generated by Django 6.0.4 on 2026-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='path_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
