# Generated by Django 6.0.4 on 2026-04-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_apiendpoint_category_apiendpoint_path_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='source_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
